if_missing = "error"

[providers]
op = { type = "1password" }

[profiles.b2.secrets]
B2_APPLICATION_KEY_ID = { provider = "op", value = "op://dev/b2uswest/MASTER_KEY_ID" }
B2_APPLICATION_KEY = { provider = "op", value = "op://dev/b2uswest/MASTER_KEY" }
GITHUB_TOKEN = { provider = "op", value = "op://iron.nokiy.net/github-reonokiy-iron/API_TOKEN" }
TF_CLOUD_HOSTNAME = { default = "app.terraform.io" }
TF_CLOUD_ORGANIZATION = { default = "reonokiy" }
TF_TOKEN_app_terraform_io = { provider = "op", value = "op://dev/terraform/API_TOKEN" }
TF_WORKSPACE = { default = "iron-default" }
TF_VAR_b2_bucket_name = { default = "flux-iron-nokiy-net" }
TF_VAR_b2_object_prefix = { default = "clusters/iron/" }
TF_VAR_b2_region = { default = "us-west-004" }
TF_VAR_cluster_name = { default = "iron" }
TF_VAR_github_owner = { default = "reonokiy" }
TF_VAR_github_repository = { default = "iron" }

[profiles."flux-bootstrap".secrets]
TF_CLOUD_HOSTNAME = { default = "app.terraform.io" }
TF_CLOUD_ORGANIZATION = { default = "reonokiy" }
TF_TOKEN_app_terraform_io = { provider = "op", value = "op://dev/terraform/API_TOKEN" }
TF_WORKSPACE = { default = "iron-flux-bootstrap" }
TF_VAR_b2_workspace = { default = "iron-default" }
TF_VAR_tfc_hostname = { default = "app.terraform.io" }
TF_VAR_tfc_organization = { default = "reonokiy" }

[profiles.civo.secrets]
CIVO_TOKEN = { provider = "op", value = "op://dev/civo/API_KEY" }
TF_CLOUD_HOSTNAME = { default = "app.terraform.io" }
TF_CLOUD_ORGANIZATION = { default = "reonokiy" }
TF_TOKEN_app_terraform_io = { provider = "op", value = "op://dev/terraform/API_TOKEN" }
TF_WORKSPACE = { default = "iron-civo" }
TF_VAR_civo_region = { default = "phx1" }
TF_VAR_cni = { default = "cilium" }
TF_VAR_cluster_name = { default = "iron" }
TF_VAR_network_label = { default = "iron" }
TF_VAR_firewall_name = { default = "iron-k8s" }
TF_VAR_kubeconfig_path = { default = "../../.kube/iron.kubeconfig" }
TF_VAR_node_pool_label = { default = "main" }
TF_VAR_node_size = { default = "g4s.kube.xsmall" }
TF_VAR_node_count = { default = "3" }
